### ISSUE TITLE
Linux: Build fails with 'SDL.h: No such file or directory'

### ISSUE THREAD

**Issue by GrieverV** [stenzek/duckstation#4]
[57/140] Building CXX object dep/imgui...les/imgui.dir/src/imgui_impl_sdl.cpp.o
    FAILED: dep/imgui/CMakeFiles/imgui.dir/src/imgui_impl_sdl.cpp.o 
    /usr/bin/c++  -DIMGUI_IMPL_OPENGL_LOADER_GLAD -Dimgui_STATIC -I../dep/imgui/include -I../dep/imgui/src -I../dep/glad/include -Wall -Wno-switch -Wno-class-memaccess -Wno-invalid-offsetof -O3 -DNDEBUG   -pthread -std=gnu++17 -MD -MT dep/imgui/CMakeFiles/imgui.dir/src/imgui_impl_sdl.cpp.o -MF dep/imgui/CMakeFiles/imgui.dir/src/imgui_impl_sdl.cpp.o.d -o dep/imgui/CMakeFiles/imgui.dir/src/imgui_impl_sdl.cpp.o -c ../dep/imgui/src/imgui_impl_sdl.cpp
    In file included from ../dep/imgui/include/imgui.h:36,
                     from ../dep/imgui/src/imgui_impl_sdl.cpp:46:
    ../dep/imgui/include/imconfig.h:16: warning: "IMGUI_IMPL_OPENGL_LOADER_GLAD" redefined
       16 | #define IMGUI_IMPL_OPENGL_LOADER_GLAD
          | 
    <command-line>: note: this is the location of the previous definition
    ../dep/imgui/src/imgui_impl_sdl.cpp:51:10: fatal error: SDL.h: No such file or directory
       51 | #include <SDL.h>
          |          ^~~~~~~
    compilation terminated.

As far as I can tell, FindSDL2.cmake isn't part of CMake which means `find_package(SDL2 REQUIRED)` doesn't work as expected and `SDL2_INCLUDE_DIRS` and `SDL2_LIBRARIES` are left unset.

Modifying the cmake files to use [FindSDL2.cmake](https://github.com/hrydgard/ppsspp/blob/master/cmake/Modules/FindSDL2.cmake) from PPSSPP allowed duckstation to successfully build on my Arch Linux system.

**Comment by stenzek** [comment]
Strange that it seems to work on my system (Ubuntu 19.04) with no find script. I guess it must be picking it up from `pkg-config`. I'll add the module anyway.

**Comment by GrieverV** [comment]
It appears it may be an issue with the SDL2Config.cmake generated when SDL2 is built with cmake:  
[https://discourse.libsdl.org/t/arch-linux-cmake-find-package-sdl2-required-passes-but-doesnt-find-anything/24226](https://discourse.libsdl.org/t/arch-linux-cmake-find-package-sdl2-required-passes-but-doesnt-find-anything/24226)  

I tried building with `set(SDL2_LIBRARIES "SDL2::SDL2")` and ran into [cmake/cmake#19531](https://gitlab.kitware.com/cmake/cmake/issues/19531) which doesn't happen when using the third-party FindSDL2.cmake module.

    [72/140] Building C object dep/nativefiledialog/CMakeFiles/nativefiledialog.dir/src/nfd_gtk.c.o
    FAILED: dep/nativefiledialog/CMakeFiles/nativefiledialog.dir/src/nfd_gtk.c.o 
    /usr/bin/cc  -I../dep/nativefiledialog/include -I../dep/nativefiledialog/src -I/usr/include/gtk-2.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/lib64/gtk-2.0/include -Wno-switch -O3 -DNDEBUG -MD -MT dep/nativefiledialog/CMakeFiles/nativefiledialog.dir/src/nfd_gtk.c.o -MF dep/nativefiledialog/CMakeFiles/nativefiledialog.dir/src/nfd_gtk.c.o.d -o dep/nativefiledialog/CMakeFiles/nativefiledialog.dir/src/nfd_gtk.c.o   -c ../dep/nativefiledialog/src/nfd_gtk.c
    In file included from /usr/include/pango-1.0/pango/pango-font.h:25,
                     from /usr/include/pango-1.0/pango/pango-attributes.h:25,
                     from /usr/include/pango-1.0/pango/pango.h:25,
                     from /usr/include/gtk-2.0/gdk/gdktypes.h:37,
                     from /usr/include/gtk-2.0/gdk/gdkscreen.h:32,
                     from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                     from /usr/include/gtk-2.0/gdk/gdk.h:32,
                     from /usr/include/gtk-2.0/gtk/gtk.h:32,
                     from ../dep/nativefiledialog/src/nfd_gtk.c:10:
    /usr/include/pango-1.0/pango/pango-coverage.h:28:10: fatal error: hb.h: No such file or directory
       28 | #include <hb.h>
          |          ^~~~~~
    compilation terminated.

Applying the upstream patch allowed duckstation to successfully build again. I have no idea what I'm doing with CMake so it may be I missed something and not just due to the upstream bug.

**Comment by stenzek** [comment]
I've added a `FindSDL2.cmake` module in-tree now, so the original issue should be fixed.

The GTK issue does seem more like an issue with the CMake script, so I'm not sure it's worth working around, especially as it appears to be fixed upstream.

**Comment by GrieverV** [comment]
Thanks! I can confirm duckstation 9da4e64 successfully builds on my Arch Linux system.
