### ISSUE TITLE
Duckstation fails to compile with GCC 11.1.0 on Linux

### ISSUE THREAD

**Issue by thedax** [stenzek/duckstation#2101]
**Game details**
[Serial Code, Region]
[i.e SLUS-00404 Ace Combat 2 (USA)]
N/A

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]

The emulator fails to compile on GCC 11 due to usage of `offsetof` that isn't accepted by the compiler.

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
2. Which controller backend are you using in general settings

N/A, N/A

**Steps to reproduce**
1. Clone the repository
2. Proceed with the usual cmake command for Linux (i.e., `cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..`)
3. Attempt to compile using GCC 11.1.0
4. Observe that it fails with the following output:

```
In file included from /usr/include/sys/mman.h:25,
                 from /home/dax/devel/duckstation/src/core/../../dep/xbyak/xbyak/xbyak.h:72,
                 from /home/dax/devel/duckstation/src/core/cpu_recompiler_types.h:13,
                 from /home/dax/devel/duckstation/src/core/cpu_code_cache.h:14,
                 from /home/dax/devel/duckstation/src/core/cpu_recompiler_code_generator.h:8,
                 from /home/dax/devel/duckstation/src/core/cpu_recompiler_code_generator.cpp:1:
/home/dax/devel/duckstation/src/core/cpu_recompiler_code_generator.cpp: In member function ‘CPU::Recompiler::Value CPU::Recompiler::CodeGenerator::DoGTERegisterRead(u32)’:
/home/dax/devel/duckstation/src/core/cpu_recompiler_code_generator.cpp:2630:87: error: ‘index’ is not a constant expression
 2630 |       EmitLoadCPUStructField(value.host_reg, RegSize_32, offsetof(State, gte_regs.r32[index]));
      |                                                                                       ^~~~~
/home/dax/devel/duckstation/src/core/cpu_recompiler_code_generator.cpp: In member function ‘void CPU::Recompiler::CodeGenerator::DoGTERegisterWrite(u32, const CPU::Recompiler::Value&)’:
/home/dax/devel/duckstation/src/core/cpu_recompiler_code_generator.cpp:2659:60: error: ‘index’ is not a constant expression
 2659 |       EmitStoreCPUStructField(offsetof(State, gte_regs.r32[index]), temp);
      |                                                            ^~~~~
/home/dax/devel/duckstation/src/core/cpu_recompiler_code_generator.cpp:2672:60: error: ‘index’ is not a constant expression
 2672 |       EmitStoreCPUStructField(offsetof(State, gte_regs.r32[index]), temp);
      |                                                            ^~~~~
/home/dax/devel/duckstation/src/core/cpu_recompiler_code_generator.cpp:2714:60: error: ‘index’ is not a constant expression
 2714 |       EmitStoreCPUStructField(offsetof(State, gte_regs.r32[index]), value);
      |                                                            ^~~~~
make[2]: *** [src/core/CMakeFiles/core.dir/build.make:719: src/core/CMakeFiles/core.dir/cpu_recompiler_code_generator.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:2121: src/core/CMakeFiles/core.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Enhancements information**
[Make sure they are all turned off before report]
N/A

**Hardware/software**
[If Android, which phone and Android version]
[If desktop, your CPU, graphics card, and operating system]
[GPU Renderer - D3D11/OpenGL/Vulkan]

AMD Ryzen 3900X
NVidia RTX 2060
Gentoo Linux
GCC version 11.1.0 (Gentoo 11.1.0 p1)

**Emulator version**
[Shown in the title bar of the emulator]

Commit `eae2883e9c`, unknown if there is a previously working commit, since I upgraded gcc only recently (2-3 days ago).

**Additional context**
[Add any other context about the problem here]

This was also an issue in Dolphin a while back: 
https://github.com/dolphin-emu/dolphin/pull/9498
https://bugs.dolphin-emu.org/issues/12409

I was able to "fix" it by changing the offending lines from using 
`offsetof(State, gte_regs.r32[index])`

to

`offsetof(State, gte_regs.r32) + sizeof(State::gte_regs.r32[0]) * index)`

but I am unsure if that's the proper and correct way of doing so. If it is, I'd be happy to submit a pull request.

**Comment by stenzek** [comment]
I wonder if this is a compiler bug... It should be fine

**Comment by stenzek** [comment]
Should be fixed with https://github.com/stenzek/duckstation/commit/bca887928bc53db5376b70a6560ecbf6b4873f43
